;;; test-page-state.el --- async page-state tests  -*- lexical-binding: t; -*-

(require 'ert)
(require 'slack-page-state)
(require 'slack-team)

(ert-deftest slack-test-page-state-commits-an-empty-page ()
  (let* ((state (slack-page-state-create))
         (generation (slack-page-state-begin state)))
    (should (eq 'loading (slack-page-state-status state)))
    (should (slack-page-state-commit state generation nil "next" t))
    (should (slack-page-state-loaded-p state))
    (should (eq 'ready (slack-page-state-status state)))
    (should-not (slack-page-state-value state))
    (should (equal "next" (slack-page-state-continuation state)))
    (should (slack-page-state-has-more state))))

(ert-deftest slack-test-page-state-coalesces-and-rejects-stale-results ()
  (let* ((state (slack-page-state-create))
         (first (slack-page-state-begin state)))
    (should-not (slack-page-state-begin state))
    (let ((second (slack-page-state-restart state)))
      (should (< first second))
      (should-not (slack-page-state-commit state first '(old) nil nil))
      (should (slack-page-state-commit state second '(new) nil nil))
      (should (equal '(new) (slack-page-state-value state))))))

(ert-deftest slack-test-page-state-refresh-preserves-stale-value-on-failure ()
  (let* ((state (slack-page-state-create))
         (first (slack-page-state-begin state)))
    (slack-page-state-commit state first '(cached) nil nil)
    (let ((second (slack-page-state-begin state t)))
      (should (eq 'refreshing (slack-page-state-status state)))
      (should (slack-page-state-fail state second 'network-error))
      (should (eq 'failed (slack-page-state-status state)))
      (should (equal '(cached) (slack-page-state-value state)))
      (should (slack-page-state-loaded-p state)))))

(ert-deftest slack-test-page-state-primary-commit-precedes-ready ()
  (let* ((state (slack-page-state-create))
         (events nil)
         (generation (slack-page-state-begin state)))
    (slack-page-state-on-commit
     state (lambda (_state) (push 'commit events)))
    (slack-page-state-on-ready
     state (lambda (_state) (push 'ready events)))
    (slack-page-state-commit state generation '(value) nil nil t)
    (should (equal '(commit) events))
    (should (slack-page-state-in-flight-p state))
    (slack-page-state-ready state generation)
    (slack-page-state-ready state generation)
    (should (equal '(ready commit) events))))

(ert-deftest slack-test-page-state-does-not-reuse-completed-error-waiter ()
  (let* ((state (slack-page-state-create))
         (errors 0)
         (first (slack-page-state-begin state)))
    (slack-page-state-on-error
     state (lambda (_state _error) (cl-incf errors)))
    (slack-page-state-commit state first '(value) nil nil)
    (let ((second (slack-page-state-begin state t)))
      (slack-page-state-fail state second 'network-error))
    (should (= 0 errors))))

(ert-deftest slack-test-page-state-terminal-results-are-final ()
  (let* ((state (slack-page-state-create))
         (first (slack-page-state-begin state)))
    (slack-page-state-commit state first '(ready) nil nil)
    (should-not (slack-page-state-fail state first 'late-error))
    (should (eq 'ready (slack-page-state-status state)))
    (let ((second (slack-page-state-restart state)))
      (slack-page-state-fail state second 'network-error)
      (should-not (slack-page-state-ready state second))
      (should-not
       (slack-page-state-commit state second '(late-value) nil nil))
      (should (eq 'failed (slack-page-state-status state)))
      (should (eq 'network-error (slack-page-state-error state)))
      (should (equal '(ready) (slack-page-state-value state))))))

(ert-deftest slack-test-page-state-does-not-retain-inactive-waiters ()
  (let ((state (slack-page-state-create)))
    (slack-page-state-on-commit state #'ignore)
    (slack-page-state-on-ready state #'ignore)
    (slack-page-state-on-error state #'ignore)
    (should-not (slack-page-state-commit-waiters state))
    (should-not (slack-page-state-ready-waiters state))
    (should-not (slack-page-state-error-waiters state))
    (let ((generation (slack-page-state-begin state)))
      (slack-page-state-commit state generation '(value) nil nil))
    (slack-page-state-on-error state #'ignore)
    (should-not (slack-page-state-error-waiters state))))

(ert-deftest slack-test-page-state-failure-discards-waiters-before-notifying ()
  (let* ((state (slack-page-state-create))
         (generation (slack-page-state-begin state))
         waiters-at-error)
    (slack-page-state-on-commit state #'ignore)
    (slack-page-state-on-ready state #'ignore)
    (slack-page-state-on-error
     state
     (lambda (failed-state _error)
       (setq waiters-at-error
             (list (slack-page-state-commit-waiters failed-state)
                   (slack-page-state-ready-waiters failed-state)
                   (slack-page-state-error-waiters failed-state)))))
    (slack-page-state-fail state generation 'network-error)
    (should (equal '(nil nil nil) waiters-at-error))))

(ert-deftest slack-test-page-state-ignores-non-function-callbacks ()
  (let ((state (slack-page-state-create)))
    (should-not (slack-page-state-on-commit state nil))
    (should-not (slack-page-state-on-ready state 'not-a-function))
    (should-not (slack-page-state-on-error state nil))
    (let ((generation (slack-page-state-begin state)))
      (should-not (slack-page-state-on-commit state nil))
      (should-not (slack-page-state-on-ready state 'not-a-function))
      (should-not (slack-page-state-on-error state nil))
      (should-not (slack-page-state-commit-waiters state))
      (should-not (slack-page-state-ready-waiters state))
      (should-not (slack-page-state-error-waiters state))
      (should (slack-page-state-commit state generation '(value) nil nil))
      (should-not (slack-page-state-on-commit state nil))
      (should-not (slack-page-state-on-ready state 'not-a-function)))
    (let ((generation (slack-page-state-restart state)))
      (should-not (slack-page-state-on-error state nil))
      (should (slack-page-state-fail state generation 'network-error))
      (should-not (slack-page-state-on-error state 'not-a-function)))))

(ert-deftest slack-test-page-state-rejects-pristine-ready ()
  (let ((state (slack-page-state-create)))
    (should-not (slack-page-state-ready state 0))
    (should (eq 'unloaded (slack-page-state-status state)))
    (should (= 0 (slack-page-state-ready-generation state)))))

(ert-deftest slack-test-page-state-commit-callback-error-does-not-stop-ready ()
  (let* ((state (slack-page-state-create))
         (generation (slack-page-state-begin state))
         (commits 0)
         (ready 0)
         warnings)
    (cl-letf (((symbol-function 'display-warning)
               (lambda (source message &optional level _buffer-name)
                 (push (list source message level) warnings))))
      (slack-page-state-on-commit
       state (lambda (_state) (cl-incf commits)))
      (slack-page-state-on-commit
       state (lambda (_state) (error "commit callback boom")))
      (slack-page-state-on-ready
       state (lambda (_state) (cl-incf ready)))
      (should (slack-page-state-commit state generation '(value) nil nil)))
    (should (= 1 commits))
    (should (= 1 ready))
    (should (eq 'ready (slack-page-state-status state)))
    (should (= 1 (length warnings)))
    (should (eq 'slack-page-state (caar warnings)))
    (should (string-match-p "commit callback boom" (cadar warnings)))
    (should (eq :error (caddar warnings)))))

(ert-deftest slack-test-page-state-ready-and-error-callbacks-are-isolated ()
  (let* ((state (slack-page-state-create))
         (generation (slack-page-state-begin state))
         (ready 0)
         (errors 0)
         warnings)
    (cl-letf (((symbol-function 'display-warning)
               (lambda (source message &optional level _buffer-name)
                 (push (list source message level) warnings))))
      (slack-page-state-on-ready
       state (lambda (_state) (cl-incf ready)))
      (slack-page-state-on-ready
       state (lambda (_state) (error "ready callback boom")))
      (slack-page-state-commit state generation '(value) nil nil)
      (setq generation (slack-page-state-restart state))
      (slack-page-state-on-error
       state (lambda (_state _error) (cl-incf errors)))
      (slack-page-state-on-error
       state (lambda (_state _error) (error "error callback boom")))
      (slack-page-state-fail state generation 'network-error))
    (should (= 1 ready))
    (should (= 1 errors))
    (should (= 2 (length warnings)))))

(ert-deftest slack-test-page-state-error-waiters-share-terminal-error ()
  (let* ((state (slack-page-state-create))
         (generation (slack-page-state-begin state))
         received-error)
    (slack-page-state-on-error
     state (lambda (_state error) (setq received-error error)))
    (slack-page-state-on-error
     state (lambda (failed-state _error)
             (slack-page-state-restart failed-state)))
    (slack-page-state-fail state generation 'network-error)
    (should (eq 'network-error received-error))
    (should (= 2 (slack-page-state-generation state)))
    (should-not (slack-page-state-error state))))

(ert-deftest slack-test-team-page-state-survives-buffer-cache-removal ()
  (let* ((team (make-instance 'slack-team))
         (first (slack-team-page-state
                 team '(search messages "query" recent desc))))
    (oset team slack-message-buffer (make-hash-table :test 'equal))
    (puthash 'temporary-buffer t (oref team slack-message-buffer))
    (clrhash (oref team slack-message-buffer))
    (should (eq first
                (slack-team-page-state
                 team '(search messages "query" recent desc))))))

(provide 'test-page-state)
;;; test-page-state.el ends here
